name: Lint => Test => Release

on: 
  push:
  release:
    types: [ created ]

jobs:
  lint-and-test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        java-version: [8]
        maven: ['3.6.3']
 
    runs-on: ${{ matrix.platform }}
    env:
      PLATFORM: ${{ matrix.platform }}
      JAVA_VERSION: ${{ matrix.java-version }}
    
    # Grant status permission for MULTI_STATUS #
    permissions:
      contents: write
      packages: read
      statuses: write
      security-events: write
 
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: adopt
          cache: maven

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.5.1
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven }}

      # Enable caching dependencies to speed up the build
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
  
      - name: Lint Code Base
        uses: github/super-linter/slim@v5.0.0
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVA: true
          VALIDATE_XML: true
          DEFAULT_BRANCH: develop
          JAVA_FILE_NAME: checkstyle.xml
      
      - name: Install Dependencies
        run: |
          latest_tag=$(git describe --abbrev=0 --tags)
          mvn clean install -Dproject.version="$latest_tag" -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version --file pom.xml

      # Run tests
      - name: Run tests with Maven
        run: |
          latest_tag=$(git describe --abbrev=0 --tags)
          mvn test -Dproject.version="$latest_tag" --batch-mode --file pom.xml

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        run: mvn com.github.ferstl:depgraph-maven-plugin:4.0.2:reactor -DgraphFormat=json -DoutputFileName=reactor.json

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: "**/jacoco.csv"
          badges-directory: .github/badges
          generate-coverage-badge: true
          coverage-badge-filename: jacoco.svg
          generate-branches-badge: true
          branches-badge-filename: branches.svg
          generate-summary: true
          summary-filename: coverage-summary.json
          coverage-label: coverage
          branches-label: branches
          colors: '#4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44'
          fail-on-coverage-decrease: true
          fail-on-branches-decrease: true

      - name: Log coverage percentage
        run: |
            echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
            echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/
  
  release:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build Assets
        run: mvn clean install --file pom.xml -Dproject.version=${{ github.event.release.tag_name }} -DskipTests=true
  
      - name: Prepare Released Files
        run: mkdir -p released-files
        working-directory: ${{ github.workspace }}
  
      - name: Copy omod to Released Files
        run: cp omod/target/mycarehub-${{ github.event.release.tag_name }}.omod released-files/
        working-directory: ${{ github.workspace }}

      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.RELEASE_PAT }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: released-files/mycarehub-${{ github.event.release.tag_name }}.omod
          tag_name: ${{ github.event.release.tag_name }}
          body_path: CHANGELOG.md
          token: ${{ secrets.RELEASE_PAT }}